### ISSUE TITLE
新規カフェを追加したら自動でFacebookデバッカーにアクセスしたい

### ISSUE THREAD

**Issue by xioota** [xioota/hcmcafe#5]

**Comment by xioota** [comment]
もしかしていらない？

**Comment by kuteken** [comment]
このissueって、何が目的で、FBデバッガにアクセスさせたいの？

FBデバッガにアクセスさせるのって、FB上のOGP情報のキャッシュクリアのためだと思うけど、新規ページであればFBから初回アクセスされるときにキャッシュは存在してないから気にしなくていいと思うよ :+1:  

SEO目的であれば、今は`sitemap.xml`がないから、新規カフェを追加する度に`sitemap.xml`を自動更新する機能を作成するということであれば、意味が通るかな :shipit:

**Comment by SawadaArca** [comment]
> FBから初回アクセスされるときにキャッシュは存在してないから

なら問題ないです！

>SEO目的であれば、今はsitemap.xmlがないから、新規カフェを追加する度にsitemap.xmlを自動更新する機能を作成するということであれば、意味が通るかな

```sitemap_generator```というgemで半自動で生成してます。面倒なのが、```$ rake sitemap:refresh```しないといけないので、結構忘れてしまいますｗ

**Comment by kuteken** [comment]
> ```sitemap_generator```というgemで半自動で生成してます。面倒なのが、```$ rake sitemap:refresh```しないといけないので、結構忘れてしまいますｗ

http://cafe.ho-chi-minh.info/sitemap.xml.gz
